when@dev: &dev
    # See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
    zenstruck_foundry:
        make_factory:
            default_namespace: 'App\Tests\Factory'
            add_hints: false
        make_story:
            default_namespace: 'App\Tests\Story'
        persistence:
            # Flush only once per call of `PersistentObjectFactory::create()`
            flush_once: true
        faker:
            locale: fr_FR

    #　If you use the `make:factory --test` command, you may need to uncomment the following.
    # See https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#generate
    services:
        App\Tests\Factory\:
            resource: '%kernel.project_dir%/tests/Factory/'
            autowire: true
            autoconfigure: true

when@test: *dev
