services:
  backend:
    build:
      context: ..
      dockerfile: ops/images/backend.Dockerfile
      target: dev
      args:
        PHP_VERSION: ${PHP_VERSION}
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
    volumes:
      - ../backend:/app
    depends_on:
      - database

  frontend:
    build:
      context: ..
      dockerfile: ops/images/frontend.Dockerfile
      target: dev
      args:
        NODE_VERSION: ${NODE_VERSION}
        NGINX_VERSION: ${NGINX_VERSION}
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ../frontend:/app
    depends_on:
      - backend

  web:
    volumes:
      - ./conf.d/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/dev:/etc/nginx/certs:ro
      - ../backend/public/uploads:/srv/uploads:ro
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - frontend
