services:
    api:
        build:
            context: ..
            dockerfile: ops/images/api.Dockerfile
            target: dev
            args:
                PHP_VERSION: ${PHP_VERSION}
        user: "${UID:-1000}:${GID:-1000}"
        environment:
            XDEBUG_MODE: ${XDEBUG_MODE:-off}
        volumes:
            - ../api:/app
        depends_on:
            - database

    webapp:
        build:
            context: ..
            dockerfile: ops/images/web.Dockerfile
            target: dev
            args:
                NODE_VERSION: ${NODE_VERSION}
                NGINX_VERSION: ${NGINX_VERSION}
        user: "${UID:-1000}:${GID:-1000}"
        volumes:
            - ../webapp:/app
        depends_on:
            - api

    web:
        environment:
            HTTPS_PORT: ${WEB_PUBLISHED_TLS_PORT:-443}
        ports:
            - "${WEB_PUBLISHED_PORT:-80}:80"
            - "${WEB_PUBLISHED_TLS_PORT:-443}:443"
        volumes:
            - ../api/public/uploads:/srv/uploads:ro
            - ./nginx/nginx.base.conf:/etc/nginx/templates/base.conf.tpl:ro
            - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/webapp:ro
            - ./nginx/nginx-entrypoint.sh:/docker-entrypoint.d/00-envsubst.sh:ro
        extra_hosts:
            - host.docker.internal:host-gateway
        depends_on:
            - webapp
