services:
  backend:
    image: ${PROJECT_NAME}-backend:${PROD_TAG}
    volumes:
      - uploads:/app/public/uploads

  web:
    image: ${PROJECT_NAME}-web:${PROD_TAG}
    volumes:
      - uploads:/srv/uploads:ro
      - certs:/etc/nginx/certs:ro
      - acme:/var/www/certbot:ro

volumes:
  uploads:
  certs:
  acme:
