services:
  backend:
    image: ${PROD_BACKEND_IMAGE:-${PROJECT_NAME}-backend:${PROD_TAG}}
    environment:
      APP_ENV: prod
    volumes:
      - uploads:/app/public/uploads

  web:
    image: ${PROD_WEB_IMAGE:-${PROJECT_NAME}-web:${PROD_TAG}}
    volumes:
      - uploads:/srv/uploads:ro
      - certs:/etc/nginx/certs:ro
      - acme:/var/www/certbot:ro

volumes:
  uploads:
  certs:
  acme:
